version: "3.3"
# docker-compose up
services:
  postgres_database:
    container_name: postgres_database
    user: "${UID}:${GID}"
    image: postgres
    restart: always
    ports:
      - 5432:5432
      - 9229:9229
    environment:
      - TZ=America/Manaus
      - PGTZ=America/Manaus
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=review-lesson
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
